#!/bin/sh
# petridish menu-bar plugin for xbar/SwiftBar.
#
# Generated by `petridish install` — edits here are overwritten on reinstall.
#
# The path below is absolute on purpose (ARCHITECTURE.md §8.3 D1/D2). xbar is
# started by the GUI session and inherits launchd's environment rather than an
# interactive shell's, so neither ~/.cargo/bin nor /opt/homebrew/bin is
# reliably on PATH and no shell rc file is ever sourced. `exec petridish
# menubar` would work in a terminal and show nothing in the menu bar.
#
# Never exit non-zero and never print nothing: xbar disables a plugin that
# errors, so every failure degrades to a visible line instead.
BIN="__PETRIDISH_PATH__"

if [ ! -x "$BIN" ]; then
    echo "🧫 ?/?"
    echo "---"
    echo "petridish binary missing at $BIN | color=#ff0000"
    echo "---"
    echo "Refresh | refresh=true"
    exit 0
fi

exec "$BIN" menubar
