[package]
name = "swab-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
git2 = "0.21.0"
gix = { version = "0.86.0", features = ["status", "revision"] }
regex = "1.13.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha1 = "0.10"
toml = "0.8"
url = "2"
wait-timeout = "0.2"
