#!/usr/bin/env bash
#
# scripts/install.sh — download prebuilt petridish/swab/petri binaries from a
# GitHub Release and put them on PATH. No Homebrew, no Rust toolchain, no
# build from source.
#
# Not generated by cargo-dist: cargo-dist's own shell installer builds one
# script per package (petridish/swab/petri separately), which would leave a
# user who ran only one of the three with a third of the product. This script
# is hand-rolled specifically to install all three together, mirroring what
# the Homebrew tap's `depends_on` chain already does for brew users.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/JKrag/petridish/master/scripts/install.sh | bash
#   curl -fsSL .../install.sh | bash -s -- --prefix /usr/local/bin
#   curl -fsSL .../install.sh | bash -s -- --version v1.0.0-beta.8
#
# After this script finishes, run `petridish install` to wire up the
# background scanner, the Claude Code hook, and (macOS only) the menu bar.

set -euo pipefail

REPO="JKrag/petridish"
INSTALL_DIR="${PETRIDISH_INSTALL_DIR:-$HOME/.local/bin}"
VERSION="${PETRIDISH_VERSION:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix)
      INSTALL_DIR="$2"
      shift 2
      ;;
    --version)
      VERSION="$2"
      shift 2
      ;;
    -h | --help)
      cat <<'USAGE'
Usage: install.sh [--prefix DIR] [--version TAG]

  --prefix DIR   Where to put the binaries (default: $HOME/.local/bin, or
                 $PETRIDISH_INSTALL_DIR if set)
  --version TAG  Install a specific release tag instead of the latest
                 (e.g. v1.0.0-beta.8), or set $PETRIDISH_VERSION
USAGE
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

# --- preflight ---

missing=()
for tool in curl tar; do
  command -v "$tool" >/dev/null 2>&1 || missing+=("$tool")
done
if ! command -v xz >/dev/null 2>&1 && ! command -v unxz >/dev/null 2>&1; then
  missing+=("xz")
fi
if ! command -v sha256sum >/dev/null 2>&1 && ! command -v shasum >/dev/null 2>&1; then
  missing+=("sha256sum or shasum")
fi
if [[ ${#missing[@]} -gt 0 ]]; then
  echo "error: missing required tool(s): ${missing[*]}" >&2
  echo "On Debian/Ubuntu:  sudo apt-get install curl tar xz-utils coreutils" >&2
  echo "On Fedora/RHEL:    sudo dnf install curl tar xz coreutils" >&2
  exit 1
fi

# --- figure out what to download ---

os="$(uname -s)"
arch="$(uname -m)"

case "$os-$arch" in
  Linux-x86_64)
    target="x86_64-unknown-linux-gnu"
    ;;
  Darwin-arm64)
    target="aarch64-apple-darwin"
    ;;
  Darwin-x86_64)
    target="x86_64-apple-darwin"
    ;;
  *)
    echo "error: no prebuilt binaries for $os $arch." >&2
    echo "That needs a Rust toolchain and 'cargo install' instead -- see" >&2
    echo "https://github.com/$REPO#installing-from-a-checkout-instead" >&2
    exit 1
    ;;
esac

if [[ -z "$VERSION" ]]; then
  echo "resolving latest release..."
  # Not /releases/latest: that endpoint excludes prereleases outright, and
  # every petridish release so far is one (still in beta) -- it 404s.
  # /releases lists newest-first regardless of prerelease status.
  VERSION="$(curl -fsSL "https://api.github.com/repos/$REPO/releases" |
    grep -o '"tag_name": *"[^"]*"' | head -1 | sed -E 's/.*"([^"]+)"$/\1/')"
  if [[ -z "$VERSION" ]]; then
    echo "error: could not resolve the latest release tag from the GitHub API." >&2
    echo "Pass one explicitly: install.sh --version v1.0.0-beta.8" >&2
    exit 1
  fi
fi

echo "installing petridish $VERSION ($target) into $INSTALL_DIR"

# --- download, verify, extract ---

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

fetch_and_verify() {
  local artifact="$1"
  local base_url="https://github.com/$REPO/releases/download/$VERSION/$artifact.tar.xz"

  curl -fsSL -o "$tmpdir/$artifact.tar.xz" "$base_url"
  curl -fsSL -o "$tmpdir/$artifact.tar.xz.sha256" "$base_url.sha256"

  (
    cd "$tmpdir"
    if command -v sha256sum >/dev/null 2>&1; then
      sha256sum -c "$artifact.tar.xz.sha256"
    else
      shasum -a 256 -c "$artifact.tar.xz.sha256"
    fi
  )

  tar -xJf "$tmpdir/$artifact.tar.xz" -C "$tmpdir"
}

mkdir -p "$INSTALL_DIR"

for artifact in "petri-dish-$target" "swab-$target" "petri-$target"; do
  echo "fetching $artifact..."
  fetch_and_verify "$artifact"
  for entry in "$tmpdir/$artifact"/*; do
    name="$(basename "$entry")"
    case "$name" in
      README.md | CHANGELOG.md | LICENSE) continue ;;
    esac
    install -m 755 "$entry" "$INSTALL_DIR/$name"
    echo "  installed $name"
  done
done

echo
echo "installed to $INSTALL_DIR: petridish, swab, swab-hook, petri"

case ":$PATH:" in
  *":$INSTALL_DIR:"*) ;;
  *)
    echo
    echo "$INSTALL_DIR is not on your PATH. Add this to your shell profile:"
    echo "  export PATH=\"$INSTALL_DIR:\$PATH\""
    ;;
esac

echo
echo "Next: run 'petridish install' to set up the background scanner and the Claude Code hook."
